packages:
  - .
  - playground

catalog:
  '@tanstack/react-query': 5.90.5
  '@types/react': ^19.1.16
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^5.0.4
  '@wagmi/core': ^3.1.0
  prool: ~0.2.3
  react: ^19.1.1
  react-dom: ^19.1.1
  typescript: ^5.9.3
  viem: ^2.46.2
  wagmi: ^3.4.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - workerd
