/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RpcWallet_revokeAccessKeyRouteImport } from './routes/rpc/wallet_revokeAccessKey'
import { Route as RpcWallet_connectRouteImport } from './routes/rpc/wallet_connect'
import { Route as RpcWallet_authorizeAccessKeyRouteImport } from './routes/rpc/wallet_authorizeAccessKey'
import { Route as RpcPersonal_signRouteImport } from './routes/rpc/personal_sign'
import { Route as RpcEth_signTypedData_v4RouteImport } from './routes/rpc/eth_signTypedData_v4'
import { Route as RpcEth_signTransactionRouteImport } from './routes/rpc/eth_signTransaction'
import { Route as RpcEth_sendTransactionSyncRouteImport } from './routes/rpc/eth_sendTransactionSync'
import { Route as RpcEth_sendTransactionRouteImport } from './routes/rpc/eth_sendTransaction'
import { Route as RpcSplatRouteImport } from './routes/rpc/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcWallet_revokeAccessKeyRoute =
  RpcWallet_revokeAccessKeyRouteImport.update({
    id: '/rpc/wallet_revokeAccessKey',
    path: '/rpc/wallet_revokeAccessKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const RpcWallet_connectRoute = RpcWallet_connectRouteImport.update({
  id: '/rpc/wallet_connect',
  path: '/rpc/wallet_connect',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcWallet_authorizeAccessKeyRoute =
  RpcWallet_authorizeAccessKeyRouteImport.update({
    id: '/rpc/wallet_authorizeAccessKey',
    path: '/rpc/wallet_authorizeAccessKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const RpcPersonal_signRoute = RpcPersonal_signRouteImport.update({
  id: '/rpc/personal_sign',
  path: '/rpc/personal_sign',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcEth_signTypedData_v4Route = RpcEth_signTypedData_v4RouteImport.update({
  id: '/rpc/eth_signTypedData_v4',
  path: '/rpc/eth_signTypedData_v4',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcEth_signTransactionRoute = RpcEth_signTransactionRouteImport.update({
  id: '/rpc/eth_signTransaction',
  path: '/rpc/eth_signTransaction',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcEth_sendTransactionSyncRoute =
  RpcEth_sendTransactionSyncRouteImport.update({
    id: '/rpc/eth_sendTransactionSync',
    path: '/rpc/eth_sendTransactionSync',
    getParentRoute: () => rootRouteImport,
  } as any)
const RpcEth_sendTransactionRoute = RpcEth_sendTransactionRouteImport.update({
  id: '/rpc/eth_sendTransaction',
  path: '/rpc/eth_sendTransaction',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rpc/$': typeof RpcSplatRoute
  '/rpc/eth_sendTransaction': typeof RpcEth_sendTransactionRoute
  '/rpc/eth_sendTransactionSync': typeof RpcEth_sendTransactionSyncRoute
  '/rpc/eth_signTransaction': typeof RpcEth_signTransactionRoute
  '/rpc/eth_signTypedData_v4': typeof RpcEth_signTypedData_v4Route
  '/rpc/personal_sign': typeof RpcPersonal_signRoute
  '/rpc/wallet_authorizeAccessKey': typeof RpcWallet_authorizeAccessKeyRoute
  '/rpc/wallet_connect': typeof RpcWallet_connectRoute
  '/rpc/wallet_revokeAccessKey': typeof RpcWallet_revokeAccessKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rpc/$': typeof RpcSplatRoute
  '/rpc/eth_sendTransaction': typeof RpcEth_sendTransactionRoute
  '/rpc/eth_sendTransactionSync': typeof RpcEth_sendTransactionSyncRoute
  '/rpc/eth_signTransaction': typeof RpcEth_signTransactionRoute
  '/rpc/eth_signTypedData_v4': typeof RpcEth_signTypedData_v4Route
  '/rpc/personal_sign': typeof RpcPersonal_signRoute
  '/rpc/wallet_authorizeAccessKey': typeof RpcWallet_authorizeAccessKeyRoute
  '/rpc/wallet_connect': typeof RpcWallet_connectRoute
  '/rpc/wallet_revokeAccessKey': typeof RpcWallet_revokeAccessKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rpc/$': typeof RpcSplatRoute
  '/rpc/eth_sendTransaction': typeof RpcEth_sendTransactionRoute
  '/rpc/eth_sendTransactionSync': typeof RpcEth_sendTransactionSyncRoute
  '/rpc/eth_signTransaction': typeof RpcEth_signTransactionRoute
  '/rpc/eth_signTypedData_v4': typeof RpcEth_signTypedData_v4Route
  '/rpc/personal_sign': typeof RpcPersonal_signRoute
  '/rpc/wallet_authorizeAccessKey': typeof RpcWallet_authorizeAccessKeyRoute
  '/rpc/wallet_connect': typeof RpcWallet_connectRoute
  '/rpc/wallet_revokeAccessKey': typeof RpcWallet_revokeAccessKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rpc/$'
    | '/rpc/eth_sendTransaction'
    | '/rpc/eth_sendTransactionSync'
    | '/rpc/eth_signTransaction'
    | '/rpc/eth_signTypedData_v4'
    | '/rpc/personal_sign'
    | '/rpc/wallet_authorizeAccessKey'
    | '/rpc/wallet_connect'
    | '/rpc/wallet_revokeAccessKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rpc/$'
    | '/rpc/eth_sendTransaction'
    | '/rpc/eth_sendTransactionSync'
    | '/rpc/eth_signTransaction'
    | '/rpc/eth_signTypedData_v4'
    | '/rpc/personal_sign'
    | '/rpc/wallet_authorizeAccessKey'
    | '/rpc/wallet_connect'
    | '/rpc/wallet_revokeAccessKey'
  id:
    | '__root__'
    | '/'
    | '/rpc/$'
    | '/rpc/eth_sendTransaction'
    | '/rpc/eth_sendTransactionSync'
    | '/rpc/eth_signTransaction'
    | '/rpc/eth_signTypedData_v4'
    | '/rpc/personal_sign'
    | '/rpc/wallet_authorizeAccessKey'
    | '/rpc/wallet_connect'
    | '/rpc/wallet_revokeAccessKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RpcSplatRoute: typeof RpcSplatRoute
  RpcEth_sendTransactionRoute: typeof RpcEth_sendTransactionRoute
  RpcEth_sendTransactionSyncRoute: typeof RpcEth_sendTransactionSyncRoute
  RpcEth_signTransactionRoute: typeof RpcEth_signTransactionRoute
  RpcEth_signTypedData_v4Route: typeof RpcEth_signTypedData_v4Route
  RpcPersonal_signRoute: typeof RpcPersonal_signRoute
  RpcWallet_authorizeAccessKeyRoute: typeof RpcWallet_authorizeAccessKeyRoute
  RpcWallet_connectRoute: typeof RpcWallet_connectRoute
  RpcWallet_revokeAccessKeyRoute: typeof RpcWallet_revokeAccessKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/wallet_revokeAccessKey': {
      id: '/rpc/wallet_revokeAccessKey'
      path: '/rpc/wallet_revokeAccessKey'
      fullPath: '/rpc/wallet_revokeAccessKey'
      preLoaderRoute: typeof RpcWallet_revokeAccessKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/wallet_connect': {
      id: '/rpc/wallet_connect'
      path: '/rpc/wallet_connect'
      fullPath: '/rpc/wallet_connect'
      preLoaderRoute: typeof RpcWallet_connectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/wallet_authorizeAccessKey': {
      id: '/rpc/wallet_authorizeAccessKey'
      path: '/rpc/wallet_authorizeAccessKey'
      fullPath: '/rpc/wallet_authorizeAccessKey'
      preLoaderRoute: typeof RpcWallet_authorizeAccessKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/personal_sign': {
      id: '/rpc/personal_sign'
      path: '/rpc/personal_sign'
      fullPath: '/rpc/personal_sign'
      preLoaderRoute: typeof RpcPersonal_signRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/eth_signTypedData_v4': {
      id: '/rpc/eth_signTypedData_v4'
      path: '/rpc/eth_signTypedData_v4'
      fullPath: '/rpc/eth_signTypedData_v4'
      preLoaderRoute: typeof RpcEth_signTypedData_v4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/eth_signTransaction': {
      id: '/rpc/eth_signTransaction'
      path: '/rpc/eth_signTransaction'
      fullPath: '/rpc/eth_signTransaction'
      preLoaderRoute: typeof RpcEth_signTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/eth_sendTransactionSync': {
      id: '/rpc/eth_sendTransactionSync'
      path: '/rpc/eth_sendTransactionSync'
      fullPath: '/rpc/eth_sendTransactionSync'
      preLoaderRoute: typeof RpcEth_sendTransactionSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/eth_sendTransaction': {
      id: '/rpc/eth_sendTransaction'
      path: '/rpc/eth_sendTransaction'
      fullPath: '/rpc/eth_sendTransaction'
      preLoaderRoute: typeof RpcEth_sendTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RpcSplatRoute: RpcSplatRoute,
  RpcEth_sendTransactionRoute: RpcEth_sendTransactionRoute,
  RpcEth_sendTransactionSyncRoute: RpcEth_sendTransactionSyncRoute,
  RpcEth_signTransactionRoute: RpcEth_signTransactionRoute,
  RpcEth_signTypedData_v4Route: RpcEth_signTypedData_v4Route,
  RpcPersonal_signRoute: RpcPersonal_signRoute,
  RpcWallet_authorizeAccessKeyRoute: RpcWallet_authorizeAccessKeyRoute,
  RpcWallet_connectRoute: RpcWallet_connectRoute,
  RpcWallet_revokeAccessKeyRoute: RpcWallet_revokeAccessKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
